---

  - block:   

    - name: see if OS needs updating
      shell: yum list updates | awk 'f;/Updated Packages/{f=1}'| awk '{ print $1; }'
      changed_when: updates.stdout_lines | length > 0
      args:
        warn: False
      register: updates

    - name: Display updates count
      debug:
        msg: "Found {{ updates.stdout_lines | length }} packages to be updated:\n\n{{ updates.stdout }}"

   
    - when:  updates.stdout_lines | length > 0
      block:

       - name: Update OS
         yum:
           name: "*"
           state: latest
      
       - name: install yum-utils
         package:
           name: yum-utils

       - name: Disable SELinux
         selinux:
           state: disabled

       - name: check if reboot required
         shell: needs-restarting -r
         failed_when: False
         register: reboot_required
         changed_when: False 

    - when: updates.stdout_lines | length > 0 and reboot_required.rc != 0
      block:

       - name: reboot system to incorporate any kernel changes
         reboot:
            connect_timeout:  120
            msg:  "System rebooting to apply changes"
            reboot_timeout:  120

